version: '3.8'

services:
  app:
    container_name: 13_potentiel_solaire_app
    image: ghcr.io/dataforgoodfr/13_potentiel_solaire_app:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_PATH: /app/database/data.duckdb
        NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: ${NEXT_PUBLIC_GOOGLE_ANALYTICS_ID}
        NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID: ${NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID}
    # Set environment variables based on the .env file
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - '3000:3000'
