default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        args: [--fix]
        types_or: [ python, pyi ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: mixed-line-ending
  # this hook use marshmallow 4.0 which break it
  # see these issuee : 
  # https://github.com/pyupio/safety/issues/711
  # https://github.com/Lucas-C/pre-commit-hooks-safety/issues/61
  # - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  #   rev: v1.3.3
  #   hooks:
  #     - id: python-safety-dependencies-check
