name: build docker for application

on:
  push:
    branches:
      - main
      - dev

jobs:
  ci-application:
    runs-on: ubuntu-latest
    env:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: ${{ vars.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID }}
      NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID: ${{ vars.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID }}
    defaults:
      run:
        shell: bash -l {0}
    
    steps:
    - uses: actions/checkout@v4

    - name: Build and publish Docker image
      run: bash ./application/publish_image.sh
